### ISSUE TITLE
Installation bug.

### ISSUE THREAD

**Issue by sinekonata** [darkstego/wakib.d#3] opened 2020-02-09 15:43 UTC
This is the stack trace of my emacs once I `git clone https://github.com/darkstego/wakib.d.git ~/.emacs.d` :

```
Debugger entered--Lisp error: (gnutls-error #<process melpa.org> -50)
  signal(gnutls-error (#<process melpa.org> -50))
  gnutls-negotiate(:process #<process melpa.org> :type gnutls-x509pki :hostname "melpa.org")
  open-gnutls-stream("melpa.org" #<buffer  *url-http-temp*> "melpa.org" 443)
  network-stream-open-tls("melpa.org" #<buffer  *url-http-temp*> "melpa.org" 443 (:type tls :nowait t))
  open-network-stream("melpa.org" #<buffer  *url-http-temp*> "melpa.org" 443 :type tls :nowait t)
  byte-code("\306\211\n\307>\203$ **(byte code interrupted by char '^@'...)**
  url-open-stream("melpa.org" #<buffer  *url-http-temp*> "melpa.org" 443)
  url-http-find-free-connection("melpa.org" 443)
  url-http([cl-struct-url "https" nil nil "melpa.org" nil "/packages/archive-contents" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-https([cl-struct-url "https" nil nil "melpa.org" nil "/packages/archive-contents" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
  url-retrieve-internal("https://melpa.org/packages/archive-contents" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) nil nil)
  url-retrieve("https://melpa.org/packages/archive-contents" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil nil nil)
  url-retrieve-synchronously("https://melpa.org/packages/archive-contents")
  url-insert-file-contents("https://melpa.org/packages/archive-contents")
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "archive-contents")
  #[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"]()
  funcall(#[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"])
  package-refresh-contents()
  (if (package-installed-p (quote use-package)) nil (package-refresh-contents) (package-install (quote use-package)))
  eval-buffer(#<buffer  *load*> nil "/home/manuel/.emacs.d/init.el" nil t)  ; Reading at buffer position 1503
  load-with-code-conversion("/home/manuel/.emacs.d/init.el" "/home/manuel/.emacs.d/init.el" t t)
  load("/home/manuel/.emacs.d/init" t t)
  #[0 "\205\262 **(interrupted again by same char '^@')**
  command-line()
  normal-top-level()
```

In case you don't have time to review this now, can I simply use your https://github.com/darkstego/wakib-keys in the mean time? I will miss out on all the packages and new implementations you made beyond just key bindings right?
Thank you and sorry about this bug.
I am using a fresh emacs 24.5.1 on Ubuntu 16.04

**Comment by darkstego** [comment] 2020-02-10 13:54
You get a bunch the packages and a few stuff that is more than basic keybindings with this package. 

Seems like a TLS bug fix issue. My guess is if you comment out or remove the lines
`(when (< (string-to-number emacs-version) 26.3)
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"))`
near the start of the file it might fix it. I will try to test it myself but that is a very old emacs version (5 years old I think). I will have to figure out how to get that running and I am not even sure if there are other parts that just won't work due to dependency on newer features.

My recommendation would be using a newer version of emacs if possible, as I feel something will break eventually.

**Comment by sinekonata** [comment] 2020-02-14 23:34
Following your advice the final message is :
```
In end of data:
js2-mode.el:12941:1:Warning: the function `c-populate-syntax-table' might not
    be defined at runtime.

Compiling file /home/manuel/.emacs.d/elpa/js2-mode-20200211.2057/js2-old-indent.el at Fri Feb 14 13:27:57 2020
```
Warnings on later boots :
```
Error (use-package): Failed to install magit: Package `emacs-25.1' is unavailable
Error (use-package): Failed to install projectile: Package `emacs-25.1' is unavailable
Error (use-package): Cannot load projectile
```

I had done everything I could to remove 24 and install the latest. Unfortunately Ubuntu overwrote that version with the officially supported at every system reboot. Even with updates disabled, it was really spooky and I almost went insane trying for days to prevent it.

   

Update : I tried this now on another computer with same OS 16.04 and so far no rollback.
After I installed emacs 26.3 (No warnings after 1st boot) :
```
Compiling file /home/manuel/.emacs.d/elpa/js2-mode-20200211.2057/js2-mode.el at Fri Feb 14 19:16:20 2020

Compiling file /home/manuel/.emacs.d/elpa/js2-mode-20200211.2057/js2-old-indent.el at Fri Feb 14 19:16:27 2020

Compiling no file at Fri Feb 14 19:16:28 2020
Warning (bytecomp): Unused lexical argument ‘arg’ [2 times]
Warning (bytecomp): assignment to free variable ‘24h/sunrise’
Warning (bytecomp): assignment to free variable ‘24h/sunset’
Warning (bytecomp): reference to free variable ‘24h/sunrise’
Warning (bytecomp): reference to free variable ‘24h/sunset’
Warning (bytecomp): assignment to free variable ‘moe-timer’
Warning (bytecomp): reference to free variable ‘moe-timer’
Warning (bytecomp): the function ‘second’ is not known to be defined.
Warning (bytecomp): the following functions are not known to be defined:
    powerline-moe-theme, powerline-default-theme, powerline-reset
Warning (bytecomp): assignment to free variable ‘git-commit-post-finish-hook’
Warning (bytecomp): the following functions are not known to be defined:
    org-element-at-point, org-outline-overlay-data,
    org-set-outline-overlay-data
Warning (bytecomp): defcustom for ‘switch-window-auto-resize-window’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘switch-window-default-window-size’ fails to specify type [2 times]
Warning (bytecomp): Unused lexical argument ‘window’
Warning (bytecomp): the following functions are not known to be defined: mc/cursor-beg,
    mc/cursor-end
Warning (bytecomp): ‘set-temporary-overlay-map’ is an obsolete function (as of 24.4); use ‘set-transient-map’ instead.
Warning (bytecomp): looking-back called with 1 argument, but requires 2-3
Warning (bytecomp): defcustom for ‘mc/mode-line’ fails to specify type [2 times]
```

I noticed a bug and don't know where else to report it :
The \*Customize Options\* buffer seems broken. Maybe it is the custom _custom.el_ file.

At any rate thank you so much for this. I'll try to learn my way into my own init.el hopefully in a few years. This is the best starting kit I could have hoped for.

**Comment by darkstego** [comment] 2020-02-15 13:31
Odd that Ubuntu was downgrading your Emacs. As expected many packages simply won't work on older versions of Emacs.

The warnings are basically part of the 1st boot/install process that come from the added packages. I have been thinking of ways of hiding it, but I didn't want to suppress warnings altogether.

The Customize Options is interesting. I hadn't been using it and didn't notice that it wasn't working. The custom.el file shouldn't be causing problems, but it might be caused by one of the packages. 

Thanks for the feedback. I will be closing this now and if I can't fix the customize option I will open a new bug for it.

**Closed as completed by darkstego** 2020-02-15 13:31 UTC
